# Custom nav
nav:
  title: "Evan's Blog"

favicon: "/source/images/favicon.ico"

# Custom background
background:
  color: "#eff0f6"
  # image: "https://cdn-images.reidosann.top/f63f15f66ec3903621bf6ed7bd4be21c.jpeg"

# Social media
social:
  # Dribbble: https://dribbble.com/clovertuan
  # Behance: https://www.behance.net/clovertuan
  # Lofter: http://clovertuan.lofter.com/
  # Instagram: https://www.instagram.com/clovertuan/
  GitHub: https://github.com/evansuner
  # Netease: https://music.163.com/#/user?id=113874197
  # Gitee: https://gitee.com/evansuner

# Custom footer
mail: reidosann@163.com
copyright: Powered by Hexo © Evan

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  Home: /
  Archive: archives
  About: about
  Search: search

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: python
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Beian ICP and gongan information for Chinese users.
beian:
  enable: true
  icp: 皖ICP备2021006467号-2

# Search
# search:
#   path: search.xml
#   field: post
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
